Bootstrapper.bindImmediate(function(){Bootstrapper.ensEvent.add(["notificationInboxAppear"],function(){var ensEventContext=this;if(ensEventContext==window)ensEventContext=undefined;var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;console.log("notificationInboxAppear detected, pass");try{var numMessages=$("#spInbxCnt").text();var s=window.s;var citiData=window.citiData||{};s.linkTrackVars="events,eVar38,eVar20";s.linkTrackEvents="event19";s.events="event19";
s.eVar38=citiData.pageName;s.eVar20="notification Inbox:"+numMessages;s.tl(this,"o",s.eVar20);s.eVar20=""}catch(e){}})},2923039,492048);
Bootstrapper.bindImmediate(function(){Bootstrapper.ensEvent.add(["notificationInboxTeaserContent"],function(){var ensEventContext=this;if(ensEventContext==window)ensEventContext=undefined;var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var citiData=window.citiData;var teasers=citiData.notificationInboxContent.teasers;console.log("notificationInboxTeaserContent detected, pass");console.log("teaser content:"+JSON.stringify(teasers));var teasersl3="";for(var i=
0;i<teasers.length;i++){var teaser=teasers[i]["teaser"+(i+1)];teasersl3=teasersl3+"niti:"+teaser.insightId+";";console.log(teasersl3)}var s=window.s;s.linkTrackVars="eVar38,list3,events";s.linkTrackEvents="event92";s.events="event92";s.eVar38=citiData.pageName;s.list3=teasersl3;s.tl(this,"o",s.list3);s.list3=""})},2923038,492049);
Bootstrapper.bindDOMLoaded(function(){Bootstrapper.ensEvent.add(["ngaCbolBankAppPageView"],function(){var ensEventContext=this;if(ensEventContext==window)ensEventContext=undefined;var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var citiData=window.citiData||{};var s=window.s||{};var channel=citiData.channel||"";var orderid=window.citiData.appID||"";var pcode=window.citiData.prodID||"";pcode=pcode.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();var pageName=window.citiData.pageName||
s.pageName||"";var appStatus=citiData.bankAppStatus||citiData.cardAppStatus||s.eVar48||window._dl.event||"";var siteSection1=window.citiData.siteSection1||s.prop1;var cuuid=window.citiData.CUUID||"na";var prospectId=window.citiData.prospectID||"";var bpsc=citiData.bankProdSourceCode||"";var bplist=bpsc.split("|");var promo=bplist[0]||s.eVar47||"";promo=promo.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();var ssv_chkpack=bplist[2]||s.eVar46||"";ssv_chkpack=ssv_chkpack.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();
var ssv_chkprod=bplist[1]||s.eVar49||citiData.prodName||"";ssv_chkprod=ssv_chkprod.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();var _pcode=promo+"-"+ssv_chkprod+"-"+ssv_chkpack||"";var t_approve="instdec_fire";var t_pend="penddec_fire";var t_dec="declinedec_fire";var t_start="app_fire";var _tValue="";var conversion="";var _orderid="";var _appStatus="";var ssv_source="BAU";if(location.pathname=="/US/ag/cards/application"){$('\x3clink rel\x3d"preconnect" href\x3d"https://p-preprd.rfihub.com"\x3e').appendTo("head");
$('\x3clink rel\x3d"preconnect" href\x3d"https://s.rfihub.com"\x3e').appendTo("head")}pageName=pageName.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();if(pageName.toLowerCase().indexOf("iaostatus")>-1)pageName="iaostatus";appStatus=appStatus.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();channel=channel.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();function getCookie(name){var value="; "+document.cookie;var parts=value.split("; "+name+"\x3d");if(parts.length==2)return parts.pop().split(";").shift()}var cookiecuuid=
getCookie("CUUID")||"";if(cookiecuuid.length>cuuid.length)cuuid=cookiecuuid;if(cuuid.length>0)cuuid="\x26ssv_cuuid\x3d"+cuuid;if(prospectId.length>0)prospectId="\x26ssv_fk1\x3d"+prospectId;if(orderid.length>0)_orderid="\x26_orderid\x3d"+orderid+"\x26ssv_appid\x3d"+orderid;if(appStatus.length>0)_appStatus="\x26ssv_status\x3d"+appStatus;if(pcode.length>0)_pcode="\x26_pcode\x3d"+pcode+"\x26ssv_fk2\x3d"+pcode;else if(_pcode.length>3){_pcode=_pcode.replace("|","-");_pcode="\x26_pcode\x3d"+_pcode}else _pcode=
"";if(bplist.length>=2)ssv_source="AVK";if(citiData.pageName.indexOf("nga cbol bank application")>-1||citiData.siteSection4.indexOf("nga")>-1)ssv_source="NGA";if(document.location.href.indexOf("mortgage")>-1){ssv_source="mortgage";if(document.location.href.indexOf("refi")>0)_pcode+="\x26ssv_product\x3drefinance";else _pcode+="\x26ssv_product\x3dpurchase"}if(document.location.href.indexOf("heloc")>-1||document.location.href.indexOf("MHE")>-1){ssv_source="heloc";_pcode+="\x26ssv_product\x3dheloc"}else if(channel.indexOf("ard")>
-1)ssv_source="cards";ssv_source="\x26ssv_source\x3d"+ssv_source;if(promo.length>1)_pcode+="\x26ssv_promo\x3d"+promo;if(ssv_chkpack.length>1)_pcode+="\x26ssv_chkpack\x3d"+ssv_chkpack;ssv_chkprod=ssv_chkprod.replace(/[^0-9a-zA-Z]/g,"").toLowerCase();if(ssv_chkprod.length>1)_pcode+="\x26ssv_chkprod\x3d"+ssv_chkprod+"\x26ssv_product\x3d"+ssv_chkprod;if(channel.indexOf("ard")>-1||siteSection1.indexOf("ard")>-1)if(appStatus.indexOf("eclin")>-1||appStatus.indexOf("rejected")>-1)_tValue=t_dec;else if(appStatus.indexOf("pend")>
-1)_tValue=t_pend;else if(appStatus.indexOf("pprov")>0||appStatus.indexOf("open")>-1||appStatus.indexOf("registrati")>0)_tValue=t_approve;else{if(pageName.toLowerCase().indexOf("formation")>-1||pageName.indexOf("applicationstar")>0)_tValue=t_start}else _tValue=pageName+appStatus;var pattDecision=new RegExp("eclin|pen|pprov|end");if(pattDecision.test(appStatus))conversion=_orderid+_appStatus;var ensSpace=Bootstrapper.ensightenOptions.publishPath;var RFdomain="p-preprd";if(ensSpace.indexOf("prod")>
0)RFdomain="s";var url="https://"+RFdomain+".rfihub.com/meta?_o\x3d17169175\x26_t\x3d"+_tValue+cuuid+prospectId+_pcode+conversion+ssv_source+"\x26_rev\x3d1";function getParameterByName(name,url){if(!url)url=window.location.href;name=name.replace(/[\[\]]/g,"\\$\x26");var regex=new RegExp("[?\x26]"+name+"(\x3d([^\x26#]*)|\x26|#|$)"),results=regex.exec(url);if(!results)return null;if(!results[2])return"";return decodeURIComponent(results[2].replace(/\+/g," "))}var cmv1=getParameterByName("cmv");if(cmv1)sessionStorage.setItem("cmv",
cmv1);var walletSeg1=getParameterByName("walletSegment");if(walletSeg1)sessionStorage.setItem("walletSegment",walletSeg1);var rCode1=getParameterByName("rCode");if(rCode1)sessionStorage.setItem("rCode",rCode1);var cmv2=sessionStorage.getItem("cmv");var walletSeg2=sessionStorage.getItem("walletSegment");var rCode2=sessionStorage.getItem("rCode");var cmv=cmv1||cmv2||"";var walletSeg=walletSeg1||walletSeg2||"";var rCode=rCode1||rCode2||"";if(cmv)url+="\x26ssv_cmv\x3d"+cmv;if(walletSeg)url+="\x26ssv_tcccham\x3d"+
walletSeg;if(rCode)url+="\x26ssv_resp\x3d"+rCode;if(ssv_source.indexOf("heloc")>-1)if(document.location.href.indexOf("LoanDetail")>-1){if(document.referrer.indexOf("MHE/WaitPage.do")>-1||document.referrer.indexOf("PreLoan")>-1||document.referrer.indexOf("debtconsolprocess")>-1)Bootstrapper.imageRequest(url)}else Bootstrapper.imageRequest(url);else Bootstrapper.imageRequest(url)})},3672877,494445);